# Generated by Django 4.2.6 on 2023-10-20 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name_category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Eksponaty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('info', models.TextField()),
                ('deep_info', models.TextField()),
                ('create_date', models.DateField()),
                ('create_place', models.CharField(default='неизвестно', max_length=20)),
                ('image', models.ImageField(upload_to='media')),
                ('catergory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.category', verbose_name='категории')),
            ],
        ),
    ]
