# Generated by Django 4.2.6 on 2023-10-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id_author', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('title_name', models.CharField(max_length=20)),
                ('content', models.TextField()),
            ],
        ),
    ]
